#!/usr/bin/env bash

# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Configure Nginx to listen on port 80
sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

# Check if Nginx is running
service nginx status

# Create a sample index.html file
echo "Hello World!" | tee /var/www/html/index.html

