#!/usr/bin/env bash
# Installs Nginx, listens on port 80, modifies the default web file

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a custom HTML file
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restart Nginx service
sudo service nginx restart

