#!/usr/bin/env bash
# Configures Nginx server to redirect /redirect_me to another page
# The redirection must be a "301 Moved Permanently"

# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create a simple index file
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Configure the redirection
redirect=$(cat <<EOF

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

EOF
)

sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart

