#!/bin/bash

# Update the Nginx default configuration file
sudo sed -i '79s/}//' /etc/nginx/sites-enabled/default

# Test the Nginx configuration
sudo nginx -t

# Restart Nginx if the configuration test is successful
if [ $? -eq 0 ]; then
    sudo service nginx restart
fi

