#!/bin/bash

# Update the system
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Modify the default web file
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Configure redirection
sudo sed -i '/server_name _;/a \\trewrite ^/redirect_me https://github.com/jesulayomy permanent;\n' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

