#!/usr/bin/env bash
# Fixes server bug to display a page

# Add ServerName directive to Apache configuration file
echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Start Apache web server
systemctl start apache2

