#!/usr/bin/env bash

# Generate school ssh key protected by passphrase
ssh-keygen -t rsa -f school -b 4096 -N betty

# Set the path to the SSH client system-wide configuration file
config_file="/etc/ssh/ssh_config"

# Add or modify the following settings in the SSH client configuration file
sudo sed -i 's/#   ProxyCommand ssh -q -W %h:%p gateway.example.com/ProxyCommand ssh -q -W %h:%p gateway.example.com/' "$config_file"
sudo sed -i 's/#   RekeyLimit 1G 1h/RekeyLimit 1G 1h/' "$config_file"
sudo sed -i '/#   SendEnv LANG LC_*/a SendEnv LANG LC_*' "$config_file"
sudo sed -i '/#   HashKnownHosts yes/a HashKnownHosts yes' "$config_file"
sudo sed -i '/#   GSSAPIAuthentication yes/a GSSAPIAuthentication yes' "$config_file"
sudo sed -i '/#   GSSAPIDelegateCredentials no/a GSSAPIDelegateCredentials no' "$config_file"
sudo sed -i '/#   IdentityFile ~/.ssh/school/a IdentityFile ~/.ssh/school' "$config_file"
sudo sed -i '/#   PasswordAuthentication no/a PasswordAuthentication no' "$config_file"

echo "SSH client configuration updated successfully!"

